version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/adamjyz/Local-Event_Explorer
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t adamjyz/around .
          docker login -u="$adamjyz" -p="$adam911911"
          docker push adamjyz/around
